language: cpp

#
# Define the build matrix
#
# Travis defaults to building on Ubuntu Trusty when building on
# Linux. We need Xenial in order to get up to date versions of
# cmake and g++.
#
env:
  global:
    - app_id=audioencoder.wav

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.1

#
# Some of the OS X images don't have cmake, contrary to what people 
# on the Internet say
#
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew install cmake; fi

#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd ${app_id} && mkdir build && cd build
  - mkdir -p definition/${app_id}
  - echo ${app_id} $TRAVIS_BUILD_DIR $TRAVIS_COMMIT > definition/${app_id}/${app_id}.txt
  - cmake -DADDONS_TO_BUILD=${app_id} -DADDON_SRC_PREFIX=$TRAVIS_BUILD_DIR/.. -DADDONS_DEFINITION_DIR=$TRAVIS_BUILD_DIR/build/definition -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../xbmc/addons -DPACKAGE_ZIP=1 $TRAVIS_BUILD_DIR/../xbmc/cmake/addons

script: make
